-- D1 Schema for the OJ Proxy Worker

-- ----------------------------
--  Table structure for "users"
-- ----------------------------
-- This table stores the whitelist of users allowed to use the proxy.
-- It also stores the user's password if they select the "Remember Me" option.
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    -- The user's unique username, used as the primary identifier.
    username TEXT PRIMARY KEY NOT NULL,
    
    -- The user's email, also required to be unique. The login can use either username or email.
    email TEXT NOT NULL UNIQUE,
    
    -- Stores the user's OJ password in plain text if "Remember Me" is checked.
    -- This field is NULL by default if the user does not opt-in.
    password TEXT
);

-- ----------------------------
--  Table structure for "sessions"
-- ----------------------------
-- This table stores active user sessions after they log in through the proxy.
DROP TABLE IF EXISTS sessions;
CREATE TABLE sessions (
    -- A unique UUID generated by the worker to identify this specific session.
    session_id TEXT PRIMARY KEY NOT NULL,
    
    -- The username associated with this session. This is unique to enforce one active session per user.
    -- The ON CONFLICT clause in the worker code relies on this uniqueness.
    username TEXT NOT NULL UNIQUE,
    
    -- The real, valid token obtained from the target OJ for this user.
    -- This token is used for all "special" API requests made on behalf of the user.
    oj_token TEXT NOT NULL,
    
    -- The timestamp when the session was created or last updated.
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ----------------------------
--  Optional Indexes
-- ----------------------------
-- While PRIMARY KEY and UNIQUE constraints automatically create indexes,
-- you can explicitly create them for clarity or other query patterns.
CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_sessions_username ON sessions (username);
